---
- name: Install prerequisites
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
    state: present
    update_cache: true

- name: Install Docker CE
  ansible.builtin.apt:
    name: docker.io
    state: present
